name: 'Azure Deployment Stacks Action'
description: 'GitHub Actions for deploying to Azure Deployment Stacks'
author: 'Lyon Till'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  name:
    description: 'The name of the deployment stack.'
    required: true
  description:
    description: 'The description of deployment stack.'
    required: false

  location:
    description: 'The location to store deployment stack.'
    required: false
    default: 'eastus'

  scope:
    description: 'The scope of the deployment stack.'
    required: true
  mode:
    description: 'The mode of the deployment stack action.'
    required: true

  actione-on-unmanage:
    description:
      'Defines what happens to resources that are no longer managed after the
      stack is updated or deleted.'
    required: false

  deny-settings:
    description:
      'Define which operations are denied on resources managed by the stack.'
    required: false
  apply-to-child-scopes:
    description: 'DenySettings will be applied to child scopes.'
    required: false
  excluded-actions:
    description:
      'List of role-based management operations that are excluded from the
      denySettings.'
    required: false
  excluded-principals:
    description: 'List of Entra principal IDs excluded from the lock.'
    required: false

  management-group-id:
    description:
      'The management group id where the deployment stack will be created.'
    required: false
  subscription-id:
    description:
      'The subscription id where the deployment stack will be created.'
    required: false
  resource-group-name:
    description:
      'The resource group name where the deployment stack will be created.'
    required: false

  template-file:
    description: 'A path to a ARM or Bicep file in the file system.'
    required: false
  template-spec:
    description: 'The template spec resource id.'
    required: false
  template-uri:
    description: 'A uri to a remote template file.'
    required: false

  parameters-file:
    description: 'A path to a ARM or Bicep paramter file in the file system.'
    required: false
  parameters:
    description: ''
    required: false
  parameters-uri:
    description: 'A uri to a remote parameters file.'
    required: false

  bypass-stack-out-of-sync-error:
    description:
      'Flag to bypass service errors that indicate the stack resource list is
      not correctly synchronized.'
    required: false
    default: 'false'

  wait:
    description: 'Wait for the deployment to complete.'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
